# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWhatssend():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_whatssend(self):
    self.driver.get("https://web.whatsapp.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".selectable-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qh0vvdkp")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"selectable-text copyable-text iq0m558w g0rxnol2\"><span class=\"selectable-text copyable-text\" data-lexical-text=\"true\">+905532640927</span></p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2IMPQ .y_sn4 .ggj6brxn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_3Uu1_ .selectable-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_3Uu1_ .to2l77zo")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"selectable-text copyable-text iq0m558w g0rxnol2\" dir=\"ltr\"><span class=\"selectable-text copyable-text\" data-lexical-text=\"true\">deneme</span></p>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".svlsagor > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".svlsagor > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qssinsw9")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
